---
title: "Culhane Computational Oncology & Cancer Genomics Lab"
---

Data is revolutionizing how we diagnose and treat cancer. Advances in sequencing allow us to spatially map and measure and the genome, transcriptome and other multi-omics of each individual single cell in a tumor. These data allow us to build a map of tumor architecture, profile the cells within the tumor and its microenviroment, understand cell-cell interactions and identify new targets for diagnosis and treatment.

## Algorithms for multi-modal analysis of cancer 'omics

Our computational oncology lab specializes in using bioinformatics, data science and artificial intelligence to analyze clincal cancer genomics data. We develop algorithms to discover new insights into how different types of tumors evolve over time, or the treatments that may be more effective against specific types of cancers. By combining these powerful analytical techniques with medical knowledge about disease progression patterns or drug efficacy rates, our labs can develop algorithms to that researchers understand disease and clinical decision support tools that help clinical teams improve patient outcomes.

## Federated Connected Cancer Data

Working with national, EU and global consortium including the European 1+ Million Genomics Data Infastructure [GDI](https://gdi.onemilliongenomes.eu) and [OHDSI](https://www.ohdsi.org) we are connecting cancer data to develop more comprehensive understanding of cancer. During the pandemic we learned the value of connecting world-wide digital health data to quickly identify trends and develop strategies to improve care. Real word data including electronic health records data compliments data from cancer clinical trial research, which typically study fixed term outcomes. Our lab lead the [eHealth Hub for Cancer]() a Higher Education Authority funded all-island program to build frameworks and computational tools to connect clinical cancer data. In connecting data we can study population level data and support the design of clinical research into new treatments or combinations of treatments that may be more effective than existing ones.

## Open Science and Open Source Software

We are an open science, open development, open source software lab who values diversity and inclusion. We share our tools to the benefit of the research community, and we benefit from those who share with us. We are in active in [Bioconductor](www.bioconductor.org), a global open source software suite which supports collaboration and sharing of bioinformatics code, data and workflows. It used by over 1 million researchrs worldwide in the analysis and interpretation of genomic data.
