---
title: "Culhane Lab"
listing:
  - id: PI
    contents: "People/PI/*.qmd"
    type: grid
    
  - id: Team
    contents: "People/Team/*.qmd"
    type: grid
    
  - id: Mentoring
    contents: "People/Mentoring/*.qmd"
    type: grid
    
  - id: Alumni
    contents: "People/Alumni/*.qmd"
    type: grid
    
    grid-columns: 3
    categories: true
    feed: true
    sort-ui: [Name]
    filter-ui: [title, Name, date, description, categories, tag]
    
grid-columns: 3
image-height: 350px
  
page-layout: full
bibliography: references.bib
---

## Principal Investigator

::: {#PI}
:::

## Team

::: {#Team}
:::

## Team (Extended)

::: {#Mentoring}
:::

## Alumni

::: {#Alumni}
:::



[Lauren Hsu](https://www.linkedin.com/in/lauren-hsu-155a282a/)\
PhD Candidate in Biostatistics at Harvard\
Publications: [@hsu2020; @Lê2021; @Hsu2023]

[Azfar Basunia](https://www.pennmedicine.org/departments-and-centers/department-of-radiology/education-and-training/residency-programs/current-residents/diagnostic-radiology-residents)\
Diagnostic Radiology Resident at Penn Medicine. Department of Radiology \
Publications: [@Ramos2017; @Meng2019; @Schwede2020]

[Chen Meng](https://www.linkedin.com/in/chen-meng-0422b226/)\
Center Leader Bioinformatics at the Bavarian Center for Biomolecular Mass Spectrometry (BayBioMS)\
Publications: [@Meng2016; @Lê2021; @Meng2019; @Meng2014; @Meng2016a; @Thorsson2019]

[Daniel Gusenleitner](https://www.linkedin.com/in/daniel-gusenleitner-2b295188/)\
Head of Computational Biology at Mercy BioAnalytics, Inc.\
Publications:[@gusenleitner2012; @Schröder2013; @Culhane2012]

[Matthew Schwede](https://www.linkedin.com/in/matthew-schwede-9a051415/)\
Hematology Oncology Fellow at Stanford University School of Medicine\
Publications: [@Wang2012; @Schwede2013; @Santagata2014; @Schwede2020; @Chittenden2010]

[Oana Zeleznik](https://www.linkedin.com/in/oanazeleznik/)\
Instructor in Medicine, Harvard Medical School and Associate Epidemiologist, Brigham and Women's Hospital\
Publications: [@Meng2016]
